# Generated by Django 5.2.4 on 2025-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_ids',
            field=models.CharField(blank=True),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
