# Generated by Django 5.2.4 on 2025-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_player_ids_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True),
        ),
    ]
