# Generated by Django 5.2.4 on 2025-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='internal_comms_port',
            field=models.IntegerField(blank=True, default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameserver_port',
            field=models.IntegerField(blank=True, default=-1, unique=True),
        ),
    ]
