# Generated by Django 5.2.4 on 2025-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_internal_comms_port_alter_game_gameserver_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='server_connected',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Connecting'), (3, 'Connected'), (4, 'Disconnected')], default=1),
        ),
    ]
